============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-7.0.1, pluggy-1.0.0 -- /usr/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.6.9', 'Platform': 'Linux-5.4.0-117-generic-x86_64-with-Ubuntu-18.04-bionic', 'Packages': {'pytest': '7.0.1', 'py': '1.11.0', 'pluggy': '1.0.0'}, 'Plugins': {'metadata': '1.11.0', 'html': '3.1.1', 'xdist': '2.4.0', 'allure-pytest': '2.8.32', 'forked': '1.4.0'}}
rootdir: /home/sergey/avito_academy/avito_python_fall_2022/Pyatkovskiy_Avito_Academy_Python/hw3
plugins: metadata-1.11.0, html-3.1.1, xdist-2.4.0, allure-pytest-2.8.32, forked-1.4.0
collecting ... collected 5 items

issue5.py::test_first_format PASSED                                      [ 20%]
issue5.py::test_second_format PASSED                                     [ 40%]
issue5.py::test_unusual_second_format PASSED                             [ 60%]
issue5.py::test_first_format_exception PASSED                            [ 80%]
issue5.py::test_second_format_exception PASSED                           [100%]

============================== 5 passed in 0.04s ===============================
